version: "3.8"
services:
  mysql:
    image: mysql:8.0
    container_name: mysql_gastos
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: sistema_gastos_clientes_db
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - red_local
volumes:
  mysql_data:
networks:
  red_local:
